
version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    volumes:
      - track_my_visits_z:/data

volumes:
  track_my_visits_z:



